<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_First name Last name GenderMale Female _743ef4</name>
   <tag></tag>
   <elementGuidId>fac29b02-9ff6-4742-974f-782600f0a4ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.form-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-container</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>First name Last name GenderMale Female In BetweenDate of birthAddressEmailPlease enter a valid email address.PasswordCompanyRoleDeveloperQAManagerTechnical ArchitectBusiness AnalystJob expectationHigh salaryNice manager/leaderExcellent colleaguesGood teamworkChance to go onsiteChallengingWays of developmentRead booksTake online coursesContribute to opensource projectsJoin tech consRead tech blogsVia discovery and experimentCommentSubmit Successfully submitted!</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;form-container&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div</value>
   </webElementXpaths>
</WebElementEntity>
